apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-smdl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-smdl
    app.kubernetes.io/part-of: tkrw-pr712-0075-0053-app
  name: devfile-sample-smdl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-smdl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-smdl
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-smdl@sha256:3b56a23bf71fa9f0c9b99c2b8dca21c5fcb7ad72ec99b9c37a6f0ea5ab2eb0f6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
